name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - run: docker build -t ghcr.io/cyberdonutskorp/pyton-app:latest .
      - run: docker push ghcr.io/cyberdonutskorp/pyton-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
